extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReport/SparkReport.html

extent.reporter.spark.viewOrder=dashboard,test,category,exception,author,device,log

screenshot.dir=target/Screenshots/
screenshot.rel.path=../Screenshots/
